language: python
cache:
  - apt
  - pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
install: "make"
script:
  - make ci
before_install:
  - pip install pipenv --upgrade
sudo: false
after_success:
  - codecov
  - coveralls
notifications:
#  slack: watchcloud:rNoT5kJJakPqwLSKuev6oa4C
